import type { Metadata } from "next";
import { primary_font } from "@/lib/fonts";
import "./globals.css";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de" suppressHydrationWarning>
      <head/>
      <body className={cn("min-h-screen bg-background antialiased", primary_font.className)}>
        {children}
      </body>
    </html>
  );
}
